ACTIVE_PROFILE: local

DATABASE_HOST: localhost
DATABASE_PORT: 5432
DATABASE_NAME: postgres
DATABASE_USERNAME: postgres
DATABASE_PASSWORD: password

JWT_SECRET: bhKfCNHBNncHFysc2Fu2MyOhVJa9L5KsqZX53CN4XCVXZrg0v6oVzSDrOca8WJcp