name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull batsavid/springboot-store:latest
      - name: Delete Old docker container
        run: sudo docker rm -f springboot_store || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name springboot_store batsavid/springboot-store:latest