name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: sudo docker pull batsavid/springboot-store:latest

      - name: Delete Old springboot_store docker container
        run: sudo docker rm -f springboot_store || true

      - name: Display Content of ENV_FILE
        run: |
          cat ${{ secrets.ENV_FILE }}

      - name: Start Or Refresh Service
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          if sudo docker ps --filter "name=store_app" --format "{{.Names}}" | grep -q "store_app"; then
            echo "store_app is running, executing custom logic..."
            sudo docker stop store_app
            sudo docker rm store_app --force
            sudo docker rmi batsavid/springboot-store:latest
            sudo docker run --env-file ${ENV_FILE} -d -p 8080:8080 --name store_app batsavid/springboot-store:latest
          else
            echo "store_app is not running, starting services with docker-compose..."
            sudo docker run --env-file ${ENV_FILE} -d -p 8080:8080 --name store_app batsavid/springboot-store:latest
          fi

#commentary
#    steps:
#      - name: Pull Docker image
#        run: sudo docker pull batsavid/springboot-store:latest
#      - name: Delete Old springboot_store docker container
#        run: sudo docker rm -f springboot_store || true
#      - name: Run Docker Container
#        run: sudo docker run -d -p 8080:8080 --name springboot_store batsavid/springboot-store:latest